server:
  port: 10010
spring:
  application:
    name: shopno7-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5  #默认30s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    instance:
      prefer-ip-address: true
      ip-address: 127.0.0.1
      instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api #路由路径前缀
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms